version: '2'

services:
  webpimage:
      build:
        dockerfile: ./Dockerfile
      restart: always
      ports:
        - "8000:8000"
      networks:
        - backend
networks:
  backend:
    driver: "bridge"


